
cluster:
  name: ${CLUSTER_NAME}

node:
  master: ${NODE_MASTER}
  data: ${NODE_DATA}
  name: ${NODE_NAME}
  ingest: ${NODE_INGEST}
  max_local_storage_nodes: ${MAX_LOCAL_STORAGE_NODES}

indices:
  memory:
    index_buffer_size: ${INDEX_BUFFER_SIZE:10%}

processors: ${PROCESSORS:1}

network.host: ${NETWORK_HOST:0.0.0.0}

path:
  data: /data/data
  logs: /data/log

bootstrap:
  memory_lock: ${MEMORY_LOCK}

http:
  enabled: ${HTTP_ENABLE}
  compression: true
  cors:
    enabled: ${HTTP_CORS_ENABLE:false}
    allow-origin: ${HTTP_CORS_ALLOW_ORIGIN:some-domain}

discovery:
  zen:
    ping.unicast.hosts: ${ZEN_UNICAST_HOSTS}
    minimum_master_nodes: ${MINIMUM_MASTER_NODES}
