cluster:
  name: ${CLUSTER_NAME}

node:
  master: ${NODE_MASTER}
  data: ${NODE_DATA}
  name: ${NODE_NAME}

network.host: ${NETWORK_HOST}

path:
  data: /data/data
  logs: /data/log

bootstrap.mlockall: ${MEMORY_LOCK}

http:
  enabled: ${HTTP_ENABLE}
  compression: true
  cors:
    enabled: ${HTTP_CORS_ENABLE:false}
    allow-origin: ${HTTP_CORS_ALLOW_ORIGIN:some-domain}

discovery:
  zen:
    minimum_master_nodes: ${MINIMUM_MASTER_NODES}
    ping.unicast.hosts: ${ZEN_UNICAST_HOSTS}